name: Publish package
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist-${{ runner.os }}-${{ matrix.target }} --find-interpreter
          sccache: 'true'
          manylinux: auto
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ runner.os }}-${{ matrix.target }}
          path: dist-${{ runner.os }}-${{ matrix.target }}

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist-${{ runner.os }}-${{ matrix.target }} --find-interpreter
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ runner.os }}-${{ matrix.target }}
          path: dist-${{ runner.os }}-${{ matrix.target }}

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x64]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          architecture: ${{ matrix.target }}
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist-${{ runner.os }}-${{ matrix.target }} --find-interpreter
          sccache: 'true'
      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ runner.os }}-${{ matrix.target }}
          path: dist-${{ runner.os }}-${{ matrix.target }}

  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build sdist
        uses: PyO3/maturin-action@v1
        with:
          command: sdist
          args: --out dist-sdist
      - name: Upload sdist
        uses: actions/upload-artifact@v6
        with:
          name: wheels-sdist
          path: dist-sdist

  publish:
    needs: [linux, macos, windows, sdist]
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/pozalabs-pydub/
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
